repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]
      name: isort (python)
- repo: local
  hooks:
  - id: unittest
    name: unittest
    entry: python -m unittest discover -s tests
    language: python
    'types': [python]
    pass_filenames: false
    stages: [commit]
