from dataclasses import dataclass


@dataclass(frozen=True)
class Column:
    name: str
    include: bool
    sort_index: int


@dataclass(frozen=True)
class DimDateColumns:
    date_key = Column('DateKey', True, 0)
    the_date = Column('TheDate', True, 1)
    iso_date_name = Column('ISODateName', True, 2)
    american_date_name = Column('AmericanDateName', True, 3)
    day_of_week_name = Column('DayOfWeekName', True, 4)
    day_of_week_abbrev = Column('DayOfWeekAbbrev', True, 5)
    month_name = Column('MonthName', True, 6)
    month_abbrev = Column('MonthAbbrev', True, 7)
    year_week_name = Column('YearWeekName', True, 8)
    year_month_name = Column('YearMonthName', True, 9)
    month_year_name = Column('MonthYearName', True, 10)
    year_quarter_name = Column('YearQuarterName', True, 11)
    year = Column('Year', True, 12)
    year_week = Column('YearWeek', True, 13)
    iso_year_week_code = Column('ISOYearWeekCode', True, 14)
    year_month = Column('YearMonth', True, 15)
    year_quarter = Column('YearQuarter', True, 16)
    day_of_week_starting_monday = Column('DayOfWeekStartingMonday', True, 17)
    day_of_week = Column('DayOfWeek', True, 18)
    day_of_month = Column('DayOfMonth', True, 19)
    day_of_quarter = Column('DayOfQuarter', True, 20)
    day_of_year = Column('DayOfYear', True, 21)
    week_of_quarter = Column('WeekOfQuarter', True, 22)
    week_of_year = Column('WeekOfYear', True, 23)
    iso_week_of_year = Column('ISOWeekOfYear', True, 24)
    month = Column('Month', True, 25)
    month_of_quarter = Column('MonthOfQuarter', True, 26)
    quarter = Column('Quarter', True, 27)
    days_in_month = Column('DaysInMonth', True, 28)
    days_in_quarter = Column('DaysInQuarter', True, 29)
    days_in_year = Column('DaysInYear', True, 30)
    day_offset_from_today = Column('DayOffsetFromToday', True, 31)
    month_offset_from_today = Column('MonthOffsetFromToday', True, 32)
    quarter_offset_from_today = Column('QuarterOffsetFromToday', True, 33)
    year_offset_from_today = Column('YearOffsetFromToday', True, 34)
    today_flag = Column('TodayFlag', True, 35)
    current_week_starting_monday_flag = Column, 36(
        'CurrentWeekStartingMondayFlag', True, 37)
    current_week_flag = Column('CurrentWeekFlag', True, 38)
    prior_week_flag = Column('PriorWeekFlag', True, 39)
    next_week_flag = Column('NextWeekFlag', True, 40)
    current_month_flag = Column('CurrentMonthFlag', True, 41)
    prior_month_flag = Column('PriorMonthFlag', True, 42)
    next_month_flag = Column('NextMonthFlag', True, 43)
    current_quarter_flag = Column('CurrentQuarterFlag', True, 44)
    prior_quarter_flag = Column('PriorQuarterFlag', True, 45)
    next_quarter_flag = Column('NextQuarterFlag', True, 46)
    current_year_flag = Column('CurrentYearFlag', True, 47)
    prior_year_flag = Column('PriorYearFlag', True, 48)
    next_year_flag = Column('NextYearFlag', True, 49)
    weekday_flag = Column('WeekdayFlag', True, 50)
    business_day_flag = Column('BusinessDayFlag', True, 51)
    company_holiday_flag = Column('CompanyHolidayFlag', True, 52)
    us_public_holiday_flag = Column('USPublicHolidayFlag', True, 53)
    first_day_of_month_flag = Column('FirstDayOfMonthFlag', True, 54)
    last_day_of_month_flag = Column('LastDayOfMonthFlag', True, 55)
    first_day_of_quarter_flag = Column('FirstDayOfQuarterFlag', True, 56)
    last_day_of_quarter_flag = Column('LastDayOfQuarterFlag', True, 57)
    first_day_of_year_flag = Column('FirstDayOfYearFlag', True, 58)
    last_day_of_year_flag = Column('LastDayOfYearFlag', True, 59)
    fraction_of_week = Column('FractionOfWeek', True, 60)
    fraction_of_month = Column('FractionOfMonth', True, 61)
    fraction_of_quarter = Column('FractionOfQuarter', True, 62)
    fraction_of_year_ = Column('FractionOfYear', True, 63)
    prior_day = Column('PriorDay', True, 64)
    next_day = Column('NextDay', True, 65)
    same_day_prior_week = Column('SameDayPriorWeek', True, 66)
    same_day_prior_month = Column('SameDayPriorMonth', True, 67)
    same_day_prior_quarter = Column('SameDayPriorQuarter', True, 68)
    same_day_prior_year = Column('SameDayPriorYear', True, 69)
    same_day_next_week = Column('SameDayNextWeek', True, 70)
    same_day_next_month = Column('SameDayNextMonth', True, 71)
    same_day_next_quarter = Column('SameDayNextQuarter', True, 72)
    same_day_next_year = Column('SameDayNextYear', True, 73)
    current_week_start = Column('CurrentWeekStart', True, 74)
    current_week_end = Column('CurrentWeekEnd', True, 75)
    current_month_start = Column('CurrentMonthStart', True, 76)
    current_month_end = Column('CurrentMonthEnd', True, 77)
    current_quarter_start = Column('CurrentQuarterStart', True, 78)
    current_quarter_end = Column('CurrentQuarterEnd', True, 79)
    current_year_start = Column('CurrentYearStart', True, 80)
    current_year_end = Column('CurrentYearEnd', True, 81)
    prior_week_start = Column('PriorWeekStart', True, 82)
    prior_week_end = Column('PriorWeekEnd', True, 83)
    prior_month_start = Column('PriorMonthStart', True, 84)
    prior_month_end = Column('PriorMonthEnd', True, 85)
    prior_quarter_start = Column('PriorQuarterStart', True, 86)
    prior_quarter_end = Column('PriorQuarterEnd', True, 87)
    prior_year_start = Column('PriorYearStart', True, 88)
    prior_year_end = Column('PriorYearEnd', True, 89)
    next_week_start = Column('NextWeekStart', True, 90)
    next_week_end = Column('NextWeekEnd', True, 91)
    next_month_start = Column('NextMonthStart', True, 92)
    next_month_end = Column('NextMonthEnd', True, 93)
    next_quarter_start = Column('NextQuarterStart', True, 94)
    next_quarter_end = Column('NextQuarterEnd', True, 95)
    next_year_start = Column('NextYearStart', True, 96)
    next_year_end = Column('NextYearEnd', True, 97)
    weekly_burnup_starting_monday = Column(
        'WeeklyBurnupStartingMonday', True, 98)
    weekly_burnup = Column('WeeklyBurnup', True, 99)
    monthly_burnup = Column('MonthlyBurnup', True, 100)
    quarterly_burnup = Column('QuarterlyBurnup', True, 101)
    yearly_burnup = Column('YearlyBurnup', True, 102)
    fiscal_month_name = Column('FiscalMonthName', True, 103)
    fiscal_month_abbrev = Column('FiscalMonthAbbrev', True, 104)
    fiscal_year_name = Column('FiscalYearWeekName', True, 105)
    fiscal_year_month_name = Column('FiscalYearMonthName', True, 106)
    fiscal_month_year_name = Column('FiscalMonthYearName', True, 107)
    fiscal_year_quarter_name = Column('FiscalYearQuarterName', True, 108)
    fiscal_year = Column('FiscalYear', True, 109)
    fiscal_year_week = Column('FiscalYearWeek', True, 110)
    fiscal_year_month = Column('FiscalYearMonth', True, 111)
    fiscal_year_quarter = Column('FiscalYearQuarter', True, 112)
    fiscal_day_of_month = Column('FiscalDayOfMonth', True, 113)
    fiscal_day_of_quarter = Column('FiscalDayOfQuarter', True, 114)
    fiscal_day_of_year = Column('FiscalDayOfYear', True, 115)
    fiscal_week_of_quarter = Column('FiscalWeekOfQuarter', True, 116)
    fiscal_week_of_year = Column('FiscalWeekOfYear', True, 117)
    fiscal_month = Column('FiscalMonth', True, 118)
    fiscal_month_of_quarter = Column('FiscalMonthOfQuarter', True, 119)
    fiscal_quarter = Column('FiscalQuarter', True, 120)
    fiscal_days_in_month = Column('FiscalDaysInMonth', True, 121)
    fiscal_days_in_quarter = Column('FiscalDaysInQuarter', True, 122)
    fiscal_days_in_year = Column('FiscalDaysInYear', True, 123)
    fiscal_current_month_flag = Column('FiscalCurrentMonthFlag', True, 124)
    fiscal_prior_month_flag = Column('FiscalPriorMonthFlag', True, 125)
    fiscal_next_month_flag = Column('FiscalNextMonthFlag', True, 126)
    fiscal_current_quarter_flag = Column('FiscalCurrentQuarterFlag', True, 127)
    fiscal_prior_quarter_flag = Column('FiscalPriorQuarterFlag', True, 128)
    fiscal_next_quarter_flag = Column('FiscalNextQuarterFlag', True, 129)
    fiscal_current_year_flag = Column('FiscalCurrentYearFlag', True, 130)
    fiscal_prior_year_flag = Column('FiscalPriorYearFlag', True, 131)
    fiscal_next_year_flag = Column('FiscalNextYearFlag', True, 132)
    fiscal_first_day_of_month_flag = Column(
        'FiscalFirstDayOfMonthFlag', True, 133)
    fiscal_last_day_of_month_flag = Column(
        'FiscalLastDayOfMonthFlag', True, 134)
    fiscal_first_day_of_quarter_flag = Column, 135(
        'FiscalFirstDayOfQuarterFlag', True, 136)
    fiscal_last_day_of_quarter_flag = Column, 137(
        'FiscalLastDayOfQuarterFlag', True, 138)
    fiscal_first_day_of_year_flag = Column(
        'FiscalFirstDayOfYearFlag', True, 139)
    fiscal_last_day_of_year_flag = Column('FiscalLastDayOfYearFlag', True, 140)
    fiscal_fraction_of_month = Column('FiscalFractionOfMonth', True, 141)
    fiscal_fraction_of_quarter = Column('FiscalFractionOfQuarter', True, 142)
    fiscal_fraction_of_year = Column('FiscalFractionOfYear', True, 143)
    fiscal_current_month_start = Column('FiscalCurrentMonthStart', True, 144)
    fiscal_current_month_end = Column('FiscalCurrentMonthEnd', True, 145)
    fiscal_current_quarter_start = Column(
        'FiscalCurrentQuarterStart', True, 146)
    fiscal_current_quarter_end = Column('FiscalCurrentQuarterEnd', True, 147)
    fiscal_current_year_start = Column('FiscalCurrentYearStart', True, 148)
    fiscal_current_year_end = Column('FiscalCurrentYearEnd', True, 149)
    fiscal_prior_month_start = Column('FiscalPriorMonthStart', True, 150)
    fiscal_prior_month_end = Column('FiscalPriorMonthEnd', True, 151)
    fiscal_prior_quarter_start = Column('FiscalPriorQuarterStart', True, 152)
    fiscal_prior_quarter_end = Column('FiscalPriorQuarterEnd', True, 153)
    fiscal_prior_year_start = Column('FiscalPriorYearStart', True, 154)
    fiscal_prior_year_end = Column('FiscalPriorYearEnd', True, 155)
    fiscal_next_month_start = Column('FiscalNextMonthStart', True, 156)
    fiscal_next_month_end = Column('FiscalNextMonthEnd', True, 157)
    fiscal_next_quarter_start = Column('FiscalNextQuarterStart', True, 158)
    fiscal_next_quarter_end = Column('FiscalNextQuarterEnd', True, 159)
    fiscal_next_year_start = Column('FiscalNextYearStart', True, 160)
    fiscal_next_year_end = Column('FiscalNextYearEnd', True, 161)
    fiscal_monthly_burnup = Column('FiscalMonthlyBurnup', True, 162)
    fiscal_quarterly_burnup = Column('FiscalQuarterlyBurnup', True, 163)
    fiscal_yearly_burnup = Column('FiscalYearlyBurnup', True, 164)
    company_holiday_name = Column('CompanyHolidayName', True, 165)
    us_public_holiday_name = Column('USPublicHolidayName', True, 166)


@dataclass(frozen=True)
class DimFiscalMonthColumns:
    month_start_key = Column('MonthStartKey', True, 0)
    month_end_key = Column('MonthEndKey', True, 1)
    month_start_date = Column('MonthStartDate', True, 2)
    month_end_date = Column('MonthEndDate', True, 3)
    month_start_iso_date_name = Column('MonthStartISODateName', True, 4)
    month_end_iso_date_name = Column('MonthEndISODateName', True, 5)
    month_start_american_date_name = Column(
        'MonthStartAmericanDateName', True, 6)
    month_end_american_date_name = Column('MonthEndAmericanDateName', True, 7)
    month_name = Column('MonthName', True, 8)
    month_abbrev = Column('MonthAbbrev', True, 9)
    month_start_year_week_name = Column('MonthStartYearWeekName', True, 10)
    month_end_year_week_name = Column('MonthEndYearWeekName', True, 11)
    year_month_name = Column('YearMonthName', True, 12)
    month_year_name = Column('MonthYearName', True, 13)
    year_quarter_name = Column('YearQuarterName', True, 14)
    year = Column('Year', True, 15)
    month_start_year_week = Column('MonthStartYearWeek', True, 16)
    month_end_year_week = Column('MonthEndYearWeek', True, 17)
    year_month = Column('YearMonth', True, 18)
    year_quarter = Column('YearQuarter', True, 19)
    month_start_day_of_quarter = Column('MonthStartDayOfQuarter', True, 20)
    month_end_day_of_quarter = Column('MonthEndDayOfQuarter', True, 21)
    month_start_day_of_year = Column('MonthStartDayOfYear', True, 22)
    month_end_day_of_year = Column('MonthEndDayOfYear', True, 23)
    month_start_week_of_quarter = Column('MonthStartWeekOfQuarter', True, 24)
    month_end_week_of_quarter = Column('MonthEndWeekOfQuarter', True, 25)
    month_start_week_of_year = Column('MonthStartWeekOfYear', True, 26)
    month_end_week_of_year = Column('MonthEndWeekOfYear', True, 27)
    month_of_quarter = Column('MonthOfQuarter', True, 28)
    quarter = Column('Quarter', True, 29)
    days_in_month = Column('DaysInMonth', True, 30)
    days_in_quarter = Column('DaysInQuarter', True, 31)
    days_in_year = Column('DaysInYear', True, 32)
    current_month_flag = Column('CurrentMonthFlag', True, 33)
    prior_month_flag = Column('PriorMonthFlag', True, 34)
    next_month_flag = Column('NextMonthFlag', True, 35)
    current_quarter_flag = Column('CurrentQuarterFlag', True, 36)
    prior_quarter_flag = Column('PriorQuarterFlag', True, 37)
    next_quarter_flag = Column('NextQuarterFlag', True, 38)
    current_year_flag = Column('CurrentYearFlag', True, 39)
    prior_year_flag = Column('PriorYearFlag', True, 40)
    next_year_flag = Column('NextYearFlag', True, 41)
    first_day_of_month_flag = Column('FirstDayOfMonthFlag', True, 42)
    last_day_of_month_flag = Column('LastDayOfMonthFlag', True, 43)
    first_day_of_quarter_flag = Column('FirstDayOfQuarterFlag', True, 44)
    last_day_of_quarter_flag = Column('LastDayOfQuarterFlag', True, 45)
    first_day_of_year_flag = Column('FirstDayOfYearFlag', True, 46)
    last_day_of_year_flag = Column('LastDayOfYearFlag', True, 47)
    month_start_fraction_of_quarter = Column(
        'MonthStartFractionOfQuarter', True, 48)
    month_end_fraction_of_quarter = Column(
        'MonthEndFractionOfQuarter', True, 49)
    month_start_fraction_of_year = Column('MonthStartFractionOfYear', True, 50)
    month_end_fraction_of_year = Column('MonthEndFractionOfYear', True, 51)
    month_start_current_quarter_start = Column(
        'MonthStartCurrentQuarterStart', True, 52)
    month_start_current_quarter_end = Column(
        'MonthStartCurrentQuarterEnd', True, 53)
    month_start_current_year_start = Column(
        'MonthStartCurrentYearStart', True, 54)
    month_start_current_year_end = Column('MonthStartCurrentYearEnd', True, 55)
    month_start_prior_month_start = Column(
        'MonthStartPriorMonthStart', True, 56)
    month_start_prior_month_end = Column('MonthStartPriorMonthEnd', True, 57)
    month_start_prior_quarter_start = Column(
        'MonthStartPriorQuarterStart', True, 58)
    month_start_prior_quarter_end = Column(
        'MonthStartPriorQuarterEnd', True, 59)
    month_start_prior_year_start = Column('MonthStartPriorYearStart', True, 60)
    month_start_prior_year_end = Column('MonthStartPriorYearEnd', True, 61)
    month_start_next_month_start = Column('MonthStartNextMonthStart', True, 62)
    month_start_next_month_end = Column('MonthStartNextMonthEnd', True, 63)
    month_start_next_quarter_start = Column(
        'MonthStartNextQuarterStart', True, 64)
    month_start_next_quarter_end = Column('MonthStartNextQuarterEnd', True, 65)
    month_start_next_year_start = Column('MonthStartNextYearStart', True, 66)
    month_start_next_year_end = Column('MonthStartNextYearEnd', True, 67)
    month_start_quarterly_burnup = Column(
        'MonthStartQuarterlyBurnup', True, 68)
    month_end_quarterly_burnup = Column('MonthEndQuarterlyBurnup', True, 69)
    month_start_yearly_burnup = Column('MonthStartYearlyBurnup', True, 70)
    month_end_yearly_burnup = Column('MonthEndYearlyBurnup', True, 71)
    company_holidays_in_month = Column('CompanyHolidaysInMonth', True, 72)
    us_public_holidays_in_month = Column('USPublicHolidaysInMonth', True, 73)


@dataclass(frozen=True)
class DimCalendarMonthColumns:
    month_start_key = Column('MonthStartKey', True, 0)
    month_end_key = Column('MonthEndKey', True, 1)
    month_start_date = Column('MonthStartDate', True, 2)
    month_end_date = Column('MonthEndDate', True, 3)
    month_start_iso_date_name = Column('MonthStartISODateName', True, 4)
    month_end_iso_date_name = Column('MonthEndISODateName', True, 5)
    month_start_american_date_name = Column(
        'MonthStartAmericanDateName', True, 6)
    month_end_american_date_name = Column('MonthEndAmericanDateName', True, 7)
    month_name = Column('MonthName', True, 8)
    month_abbrev = Column('MonthAbbrev', True, 9)
    month_start_year_week_name = Column('MonthStartYearWeekName', True, 10)
    month_end_year_week_name = Column('MonthEndYearWeekName', True, 11)
    year_month_name = Column('YearMonthName', True, 12)
    month_year_name = Column('MonthYearName', True, 13)
    year_quarter_name = Column('YearQuarterName', True, 14)
    year = Column('Year', True, 15)
    month_start_year_week = Column('MonthStartYearWeek', True, 16)
    month_end_year_week = Column('MonthEndYearWeek', True, 17)
    year_month = Column('YearMonth', True, 18)
    year_quarter = Column('YearQuarter', True, 19)
    month_start_day_of_quarter = Column('MonthStartDayOfQuarter', True, 20)
    month_end_day_of_quarter = Column('MonthEndDayOfQuarter', True, 21)
    month_start_day_of_year = Column('MonthStartDayOfYear', True, 22)
    month_end_day_of_year = Column('MonthEndDayOfYear', True, 23)
    month_start_week_of_quarter = Column('MonthStartWeekOfQuarter', True, 24)
    month_end_week_of_quarter = Column('MonthEndWeekOfQuarter', True, 25)
    month_start_week_of_year = Column('MonthStartWeekOfYear', True, 26)
    month_end_week_of_year = Column('MonthEndWeekOfYear', True, 27)
    month_of_quarter = Column('MonthOfQuarter', True, 28)
    quarter = Column('Quarter', True, 29)
    days_in_month = Column('DaysInMonth', True, 30)
    days_in_quarter = Column('DaysInQuarter', True, 31)
    days_in_year = Column('DaysInYear', True, 32)
    current_month_flag = Column('CurrentMonthFlag', True, 33)
    prior_month_flag = Column('PriorMonthFlag', True, 34)
    next_month_flag = Column('NextMonthFlag', True, 35)
    current_quarter_flag = Column('CurrentQuarterFlag', True, 36)
    prior_quarter_flag = Column('PriorQuarterFlag', True, 37)
    next_quarter_flag = Column('NextQuarterFlag', True, 38)
    current_year_flag = Column('CurrentYearFlag', True, 39)
    prior_year_flag = Column('PriorYearFlag', True, 40)
    next_year_flag = Column('NextYearFlag', True, 41)
    first_day_of_month_flag = Column('FirstDayOfMonthFlag', True, 42)
    last_day_of_month_flag = Column('LastDayOfMonthFlag', True, 43)
    first_day_of_quarter_flag = Column('FirstDayOfQuarterFlag', True, 44)
    last_day_of_quarter_flag = Column('LastDayOfQuarterFlag', True, 45)
    first_day_of_year_flag = Column('FirstDayOfYearFlag', True, 46)
    last_day_of_year_flag = Column('LastDayOfYearFlag', True, 47)
    month_start_fraction_of_quarter = Column(
        'MonthStartFractionOfQuarter', True, 48)
    month_end_fraction_of_quarter = Column(
        'MonthEndFractionOfQuarter', True, 49)
    month_start_fraction_of_year = Column('MonthStartFractionOfYear', True, 50)
    month_end_fraction_of_year = Column('MonthEndFractionOfYear', True, 51)
    month_start_current_quarter_start = Column(
        'MonthStartCurrentQuarterStart', True, 52)
    month_start_current_quarter_end = Column(
        'MonthStartCurrentQuarterEnd', True, 53)
    month_start_current_year_start = Column(
        'MonthStartCurrentYearStart', True, 54)
    month_start_current_year_end = Column('MonthStartCurrentYearEnd', True, 55)
    month_start_prior_month_start = Column(
        'MonthStartPriorMonthStart', True, 56)
    month_start_prior_month_end = Column('MonthStartPriorMonthEnd', True, 57)
    month_start_prior_quarter_start = Column(
        'MonthStartPriorQuarterStart', True, 58)
    month_start_prior_quarter_end = Column(
        'MonthStartPriorQuarterEnd', True, 59)
    month_start_prior_year_start = Column('MonthStartPriorYearStart', True, 60)
    month_start_prior_year_end = Column('MonthStartPriorYearEnd', True, 61)
    month_start_next_month_start = Column('MonthStartNextMonthStart', True, 62)
    month_start_next_month_end = Column('MonthStartNextMonthEnd', True, 63)
    month_start_next_quarter_start = Column(
        'MonthStartNextQuarterStart', True, 64)
    month_start_next_quarter_end = Column('MonthStartNextQuarterEnd', True, 65)
    month_start_next_year_start = Column('MonthStartNextYearStart', True, 66)
    month_start_next_year_end = Column('MonthStartNextYearEnd', True, 67)
    month_start_quarterly_burnup = Column(
        'MonthStartQuarterlyBurnup', True, 68)
    month_end_quarterly_burnup = Column('MonthEndQuarterlyBurnup', True, 69)
    month_start_yearly_burnup = Column('MonthStartYearlyBurnup', True, 70)
    month_end_yearly_burnup = Column('MonthEndYearlyBurnup', True, 71)
    company_holidays_in_month = Column('CompanyHolidaysInMonth', True, 72)
    us_public_holidays_in_month = Column('USPublicHolidaysInMonth', True, 73)
