CREATE TABLE dbo.DimCalendarMonth (
  MonthStartKey int NOT NULL,
  MonthEndKey int NOT NULL,
  MonthStartDate date NOT NULL,
  MonthEndDate date NOT NULL,
  MonthStartISODateName varchar(10) NOT NULL,
  MonthEndISODateName varchar(10) NOT NULL,
  MonthStartAmericanDateName varchar(10) NOT NULL,
  MonthEndAmericanDateName varchar(10) NOT NULL,
  MonthName varchar(9) NOT NULL,
  MonthAbbrev varchar(3) NOT NULL,
  MonthStartYearWeekName varchar(8) NOT NULL,
  MonthEndYearWeekName varchar(8) NOT NULL,
  YearMonthName varchar(7) NOT NULL,
  MonthYearName varchar(8) NOT NULL,
  YearQuarterName varchar(6) NOT NULL,
  Year int NOT NULL,
  MonthStartYearWeek int NOT NULL,
  MonthEndYearWeek int NOT NULL,
  YearMonth int NOT NULL,
  YearQuarter int NOT NULL,
  MonthStartDayOfQuarter int NOT NULL,
  MonthEndDayOfQuarter int NOT NULL,
  MonthStartDayOfYear int NOT NULL,
  MonthEndDayOfYear int NOT NULL,
  MonthStartWeekOfQuarter int NOT NULL,
  MonthEndWeekOfQuarter int NOT NULL,
  MonthStartWeekOfYear int NOT NULL,
  MonthEndWeekOfYear int NOT NULL,
  MonthOfQuarter int NOT NULL,
  Quarter int NOT NULL,
  DaysInMonth int NOT NULL,
  DaysInQuarter int NOT NULL,
  DaysInYear int NOT NULL,
  CurrentMonthFlag bit NOT NULL,
  PriorMonthFlag bit NOT NULL,
  NextMonthFlag bit NOT NULL,
  CurrentQuarterFlag bit NOT NULL,
  PriorQuarterFlag bit NOT NULL,
  NextQuarterFlag bit NOT NULL,
  CurrentYearFlag bit NOT NULL,
  PriorYearFlag bit NOT NULL,
  NextYearFlag bit NOT NULL,
  FirstDayOfMonthFlag bit NOT NULL,
  LastDayOfMonthFlag bit NOT NULL,
  FirstDayOfQuarterFlag bit NOT NULL,
  LastDayOfQuarterFlag bit NOT NULL,
  FirstDayOfYearFlag bit NOT NULL,
  LastDayOfYearFlag bit NOT NULL,
  MonthStartFractionOfQuarter decimal(5,4)
    CONSTRAINT chk_DimCalendarMonth_MonthStartFractionOfQuarter CHECK (MonthStartFractionOfQuarter BETWEEN 0 AND 1)
    NOT NULL,
  MonthEndFractionOfQuarter decimal(5,4)
    CONSTRAINT chk_DimCalendarMonth_MonthEndFractionOfQuarter CHECK (MonthEndFractionOfQuarter BETWEEN 0 AND 1)
    NOT NULL,
  MonthStartFractionOfYear decimal(5,4)
    CONSTRAINT chk_DimCalendarMonth_MonthStartFractionOfYear CHECK (MonthStartFractionOfYear BETWEEN 0 AND 1)
    NOT NULL,
  MonthEndFractionOfYear decimal(5,4)
    CONSTRAINT chk_DimCalendarMonth_MonthEndFractionOfYear CHECK (MonthEndFractionOfYear BETWEEN 0 AND 1)
    NOT NULL,
  MonthStartCurrentQuarterStart date NOT NULL,
  MonthStartCurrentQuarterEnd date NOT NULL,
  MonthStartCurrentYearStart date NOT NULL,
  MonthStartCurrentYearEnd date NOT NULL,
  MonthStartPriorMonthStart date NOT NULL,
  MonthStartPriorMonthEnd date NOT NULL,
  MonthStartPriorQuarterStart date NOT NULL,
  MonthStartPriorQuarterEnd date NOT NULL,
  MonthStartPriorYearStart date NOT NULL,
  MonthStartPriorYearEnd date NOT NULL,
  MonthStartNextMonthStart date NOT NULL,
  MonthStartNextMonthEnd date NOT NULL,
  MonthStartNextQuarterStart date NOT NULL,
  MonthStartNextQuarterEnd date NOT NULL,
  MonthStartNextYearStart date NOT NULL,
  MonthStartNextYearEnd date NOT NULL,
  MonthStartQuarterlyBurnup bit NOT NULL,
  MonthEndQuarterlyBurnup bit NOT NULL,
  MonthStartYearlyBurnup bit NOT NULL,
  MonthEndYearlyBurnup bit NOT NULL,
  CompanyHolidaysInMonth int NOT NULL,
  USPublicHolidaysInMonth int NOT NULL
);
